/**
 * The reference's API paths as the owner's capture saw them (STORY_004).
 * Paths only: resource timing gives no methods and no bodies, and the
 * generation, upload and status calls were not observed at all. The
 * rendered files say so, so the list is never mistaken for the protocol.
 */
import { stripQuery } from "./curate-model.ts";

export type Endpoint = { group: string; host: string; path: string; note?: string };

export type EndpointSource = {
  source: string;
  method_note: string;
  endpoints: Record<string, Array<{ host: string; path: string; likely?: string; also?: string }>>;
  not_observed: string[];
  not_observed_reason: string;
  skipped: string[];
};

/** Hosts that are never product API: analytics, anti-bot, CDN assets and generated media. */
export const NOISE_HOSTS = ["aplus.qwen.ai", "ss.qwen.ai", "assets.alicdn.com", "img.alicdn.com", "cdn.qwenlm.ai", "g.alicdn.com", "www.googletagmanager.com"];

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function placeholders(path: string): string {
  return stripQuery(path)
    .split("/")
    .map((seg) => {
      if (UUID.test(seg)) return ":uuid";
      if (/^\d{6,}$/.test(seg)) return ":id";
      if (/^[0-9a-f]{16,}$/i.test(seg)) return ":hex";
      return seg;
    })
    .join("/");
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function parseEndpointSource(v: unknown): EndpointSource {
  if (!isRecord(v) || !isRecord(v.endpoints) || !Array.isArray(v.not_observed)) throw new Error("network-endpoints.json: missing endpoints or not_observed");
  const strings = (x: unknown): string[] => (Array.isArray(x) ? x.filter((s): s is string => typeof s === "string") : []);
  const endpoints: EndpointSource["endpoints"] = {};
  for (const [group, list] of Object.entries(v.endpoints)) {
    if (!Array.isArray(list)) continue;
    endpoints[group] = list.filter(isRecord).flatMap((e) =>
      typeof e.host === "string" && typeof e.path === "string"
        ? [{ host: e.host, path: e.path, ...(typeof e.likely === "string" ? { likely: e.likely } : {}), ...(typeof e.also === "string" ? { also: e.also } : {}) }]
        : [],
    );
  }
  return {
    source: typeof v.source === "string" ? v.source : "",
    method_note: typeof v.method_note === "string" ? v.method_note : "",
    endpoints,
    not_observed: strings(v.not_observed),
    not_observed_reason: typeof v.not_observed_reason === "string" ? v.not_observed_reason : "",
    skipped: strings(v.skipped),
  };
}

/** Groups in the source's order, paths placeholdered, noise hosts dropped, duplicates removed. */
export function endpoints(src: EndpointSource): Endpoint[] {
  const out: Endpoint[] = [];
  const seen = new Set<string>();
  for (const [group, list] of Object.entries(src.endpoints)) {
    for (const e of list) {
      if (NOISE_HOSTS.includes(e.host)) continue;
      const path = placeholders(e.path);
      const key = `${e.host}${path}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const notes = [e.likely ? `likely ${e.likely}` : "", e.also ? `also sent as a ${e.also}` : ""].filter((x) => x !== "");
      out.push({ group, host: e.host, path, ...(notes.length > 0 ? { note: notes.join("; ") } : {}) });
    }
  }
  return out;
}

export function endpointsJson(src: EndpointSource, list: Endpoint[], date: string): string {
  const doc = {
    date,
    source: src.source,
    methods: src.method_note,
    endpoints: list,
    not_observed: src.not_observed,
    not_observed_reason: src.not_observed_reason,
    excluded: src.skipped,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

export function renderEndpoints(src: EndpointSource, list: Endpoint[], date: string): string {
  const L = [
    `# Reference API paths seen on ${date}`,
    "",
    "Generated by `recon/run.sh interactions`; do not edit by hand.",
    "",
    `**This is not the protocol.** Source: ${src.source}. ${src.method_note}.`,
    "",
    "**Not observed:**",
    "",
    ...src.not_observed.map((n) => `- ${n}`),
    "",
    `Why: ${src.not_observed_reason}.`,
    "",
    "| Group | Host | Path | Note |",
    "| --- | --- | --- | --- |",
    ...list.map((e) => `| ${e.group} | ${e.host} | \`${e.path}\` | ${e.note ?? ""} |`),
    "",
    `Excluded: ${src.skipped.join("; ")}.`,
    "",
  ];
  return L.join("\n");
}
