/**
 * The component inventory (STORY_004): every reading's component tree as a
 * nested list, with each sprite icon it names linked to its harvested file.
 */
import type { Component, Reading } from "./curate-model.ts";

/** EPIC_001's flow order; states not listed sort after these, alphabetically. */
export const FLOW_ORDER = [
  "home-signed-in",
  "mode-menu-open",
  "composer-image-mode",
  "image-model-open",
  "aspect-ratio-open",
  "composer-typed",
  "composer-reference-attached",
  "job-submitted",
  "job-generating",
  "job-done",
  "edit-done",
  "my-library",
];

export function orderReadings<T extends { state: string; viewport: { width: number } }>(readings: T[]): T[] {
  const rank = (s: string): number => {
    const i = FLOW_ORDER.indexOf(s);
    return i >= 0 ? i : FLOW_ORDER.length;
  };
  return [...readings].sort((a, b) => b.viewport.width - a.viewport.width || rank(a.state) - rank(b.state) || a.state.localeCompare(b.state));
}

/** Maps `symbol #<id>` origins in assets/index.json to their paths. */
export function iconFilesFromIndex(index: unknown): Map<string, string> {
  const out = new Map<string, string>();
  if (typeof index !== "object" || index === null || !("files" in index) || !Array.isArray(index.files)) return out;
  for (const f of index.files) {
    if (typeof f !== "object" || f === null) continue;
    const origin = "origin" in f && typeof f.origin === "string" ? f.origin : "";
    const p = "path" in f && typeof f.path === "string" ? f.path : "";
    const m = /^symbol #(.+)$/.exec(origin);
    if (m?.[1] && p) out.set(m[1], p);
  }
  return out;
}

const SPRITE_ID = /\b(?:qwpcicon|appicon|qwcoloricon|qwenFileicon)-[A-Za-z0-9_-]+/g;

/** Sprite ids named in a component's own fields (not its children), trimmed back to a known id when prose follows. */
export function spriteIds(component: Component, known: ReadonlyMap<string, string>): { resolved: string[]; unresolved: string[] } {
  const resolved = new Set<string>();
  const unresolved = new Set<string>();
  for (const [key, value] of Object.entries(component)) {
    if (key === "children" || typeof value !== "string") continue;
    for (const m of value.matchAll(SPRITE_ID)) {
      let id = m[0];
      while (id.length > 0 && !known.has(id)) id = id.slice(0, -1);
      if (known.has(id)) resolved.add(id);
      // A match ending in "-" is a template in prose ("qwpcicon-a-<w>by<h>AspectRatio"), not an id.
      else if (!m[0].endsWith("-")) unresolved.add(m[0]);
    }
  }
  return { resolved: [...resolved].sort(), unresolved: [...unresolved].sort() };
}

function size(box: Component["box"]): string {
  if (typeof box !== "object" || box === null) return "";
  const w = typeof box.width === "number" ? box.width : undefined;
  const h = typeof box.height === "number" ? box.height : undefined;
  if (w !== undefined && h !== undefined) return `${w}×${h}`;
  if (w !== undefined) return `${w} wide`;
  if (h !== undefined) return `${h} tall`;
  return "";
}

export function renderInventory(readings: Reading[], icons: ReadonlyMap<string, string>, date: string): string {
  const L = [
    `# Component inventory, ${date}`,
    "",
    "Generated by `recon/run.sh interactions` from `states/`; do not edit by hand. Each entry: name, selector, size in CSS px, and the harvested icon files it uses. Full styles are in the reading itself.",
    "",
  ];
  const unresolved = new Map<string, Set<string>>();
  const walk = (c: Component, depth: number, label: string): void => {
    const name = typeof c.name === "string" && c.name !== "" ? c.name : typeof c.text === "string" ? `"${c.text}"` : "(unnamed)";
    const parts = [`**${name}**`];
    if (typeof c.selector === "string" && c.selector !== "") parts.push(`\`${c.selector}\``);
    const sz = size(c.box);
    if (sz) parts.push(sz);
    const ids = spriteIds(c, icons);
    if (ids.resolved.length > 0) parts.push(`icons: ${ids.resolved.map((id) => `[${id}](assets/${icons.get(id)})`).join(", ")}`);
    for (const u of ids.unresolved) unresolved.set(u, (unresolved.get(u) ?? new Set()).add(label));
    L.push(`${"  ".repeat(depth)}- ${parts.join(" · ")}`);
    if (Array.isArray(c.children)) for (const k of c.children) walk(k, depth + 1, label);
  };
  let width = 0;
  for (const r of orderReadings(readings)) {
    if (r.viewport.width !== width) {
      width = r.viewport.width;
      L.push(`## At ${width} px`, "");
    }
    const label = `${r.state}@${r.viewport.width}`;
    L.push(`### ${r.state}`, "", `From [states/${label}.json](states/${label}.json), URL path \`${r.url_path}\`.`, "");
    for (const c of r.components) walk(c, 0, label);
    L.push("");
  }
  L.push("## Unresolved icon ids", "");
  if (unresolved.size === 0) L.push("None: every sprite id named in a reading has a harvested file.", "");
  else for (const [id, where] of [...unresolved.entries()].sort()) L.push(`- \`${id}\` (named in ${[...where].sort().join(", ")})`);
  L.push("");
  return L.join("\n");
}
